### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ksqsf** [ksqsf/queekr#1]
This issue tracks the design of Queekr.

**Comment by ksqsf** [comment]
# Name
Queekr is a play on the name of "Twitter" by simply replacing all /t/ with /k/. The last "e" was removed to make it look better.

# What is Queekr
Queekr <del>is</del> will be a microblog client, which only relies on open technologies, like RSS/Atom feeds, HTTP.

# The Architecture of Queekr
Queekr is simply a wrapper around RSS/Atom feeds.

A simple set-up of Queekr is like:
* Set up a blog platform
* Create a page called Queekr
* Use the feed of comments as source of tweets
* Add the feed to Queekr

# Tasks
- [ ] Client-side
- [ ] Blog integration with WordPress, Typecho?
- [ ] Server-side: Queekr-server?
- [ ] Cloud converter: converts feed to a twitter-like page.
- [ ] Some sort of notification mechanism: how do I know there are new followers? how to comment? how to retweet?

**Comment by ksqsf** [comment]
Queekr is intended to be a side product of learning GNOME programming! While I'm really busy this term, I'll allow me to work on it at most two hours a day! 😄

**Comment by ksqsf** [comment]
Some proposals are "rejected for 1.0". This is because they have nothing to do with Queekr's core philosophy and concerns, and their use cases are very limited.

These proposals might be proposed and discussed again for 2.0.
